(function(){
  const moods=[['happy','开心','😊'],['calm','平静','😌'],['hopeful','期待','✨'],['tired','疲惫','😮‍💨'],['anxious','焦虑','😟'],['sad','难过','😢'],['angry','生气','😤']];
  const triggers=['学业','工作','关系','家庭','健康','睡眠','自我期待'];
  const KEY='xinyu.entries.v1'; let selectedMood='',selectedTriggers=[];
  const $=s=>document.querySelector(s); const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fallbackCare={happy:[['✦','留住这一刻','写下今天值得感谢的一件小事。','2 分钟'],['♫','延续轻盈','听一首让你想轻轻摇摆的歌。','一首歌'],['↗','舒展能量','起身伸展，让愉快也被身体记住。','3 分钟']],calm:[['◌','安静呼吸','吸气 4 秒，呼气 6 秒，重复 5 次。','1 分钟'],['♫','柔和背景','选择无歌词、节奏稳定的音乐。','5 分钟'],['✎','片刻记录','写下此刻让你平静的三个细节。','3 分钟']]};
  const defaultCare=fallbackCare.calm;
  function getEntries(){try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch(e){return[]}}
  function saveEntries(v){try{localStorage.setItem(KEY,JSON.stringify(v));return true}catch(e){return false}}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
  function renderMood(){const grid=$('.mood-grid');grid.innerHTML=moods.map(([id,name,emoji])=>`<button type="button" class="mood-btn" data-mood="${id}" aria-pressed="false"><span>${emoji}</span><small>${name}</small></button>`).join('');grid.addEventListener('click',e=>{const b=e.target.closest('[data-mood]');if(!b)return;selectedMood=b.dataset.mood;grid.querySelectorAll('button').forEach(x=>{const on=x===b;x.classList.toggle('selected',on);x.setAttribute('aria-pressed',on)});renderCare()})}
  function renderTriggers(){const box=$('#triggerList');box.innerHTML=triggers.map(x=>`<button type="button" class="trigger-chip" data-trigger="${x}" aria-pressed="false">${x}</button>`).join('');box.addEventListener('click',e=>{const b=e.target.closest('[data-trigger]');if(!b)return;const v=b.dataset.trigger;selectedTriggers=selectedTriggers.includes(v)?selectedTriggers.filter(x=>x!==v):[...selectedTriggers,v];b.classList.toggle('selected');b.setAttribute('aria-pressed',b.classList.contains('selected'))})}
  function getCare(){const moodData=window.XINYU_CARE_CONTENT&&window.XINYU_CARE_CONTENT.moods&&window.XINYU_CARE_CONTENT.moods[selectedMood];if(moodData&&moodData.care)return [['◌','一分钟停靠',moodData.care.meditation,'1 到 2 分钟'],['♫','给耳朵一点空间',moodData.care.music,'一首歌'],['↗','让身体动一点',moodData.care.movement,'3 到 10 分钟']];return fallbackCare[selectedMood]||defaultCare}
  function renderCare(){const mood=moods.find(x=>x[0]===selectedMood);$('#careIntro').textContent=mood?`为“${mood[1]}”准备的三个小行动，你只需要选择一个。`:'选择情绪后，会为你准备三个低门槛的小行动。';$('#careGrid').innerHTML=getCare().map((x,i)=>`<article class="care-item"><div class="care-icon">${esc(x.icon||x[0])}</div><h3>${esc(x.title||x[1])}</h3><p>${esc(x.text||x[2])}</p><div class="care-meta"><span>${esc(x.duration||x[3])}</span><span>${i===0?'现在可以开始':'按自己的节奏'}</span></div></article>`).join('')}
  function renderHistory(){const entries=getEntries();$('#entryCount').textContent=entries.length;$('#clearAll').hidden=!entries.length;$('#historyList').innerHTML=entries.length?entries.slice().reverse().map(e=>{const m=moods.find(x=>x[0]===e.mood)||['','未标记','◌'];return `<article class="history-item"><header><div class="history-mood"><span>${m[2]}</span><div><strong>${m[1]} · ${e.intensity}/5</strong><br><time>${new Date(e.createdAt).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</time></div></div><button class="delete-btn" data-delete="${esc(e.id)}">删除</button></header>${e.journal?`<p>${esc(e.journal)}</p>`:''}<div class="history-tags">${(e.triggers||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div></article>`}).join(''):'<div class="empty-state">还没有记录。第一份心情，不需要写得完整。</div>'}
  $('#moodForm').addEventListener('submit',e=>{e.preventDefault();if(!selectedMood){$('#formError').textContent='先选择一个最接近的情绪吧。';return}const note=$('#journal').value.trim(),crisis=window.XINYU_CARE_CONTENT&&window.XINYU_CARE_CONTENT.crisis;if(crisis&&crisis.keywords.some(k=>note.includes(k)))$('#safetyDialog').showModal();const entries=getEntries();entries.push({id:(crypto.randomUUID?crypto.randomUUID():Date.now().toString()),createdAt:new Date().toISOString(),mood:selectedMood,intensity:Number($('#intensity').value),journal:note,triggers:selectedTriggers});if(!saveEntries(entries)){toast('未能保存，请先复制文字后重试');return}$('#formError').textContent='';$('#journal').value='';$('#charCount').textContent='0 / 1000';renderHistory();toast('已收藏这一刻');if(!$('#safetyDialog').open)$('#care').scrollIntoView({behavior:'smooth'})});
  $('#historyList').addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b||!confirm('删除这条心情记录吗？'))return;saveEntries(getEntries().filter(x=>x.id!==b.dataset.delete));renderHistory();toast('记录已删除')});
  $('#clearAll').addEventListener('click',()=>{if(confirm('确定清空这台设备上的全部心情记录吗？')){saveEntries([]);renderHistory();toast('记录已清空')}});
  $('#intensity').addEventListener('input',e=>{$('#intensityValue').textContent=[,'1 · 轻轻掠过','2 · 有一点','3 · 有些明显','4 · 很强烈','5 · 几乎占满'][e.target.value]});$('#journal').addEventListener('input',e=>$('#charCount').textContent=`${e.target.value.length} / 1000`);
  function drawTarot(){const deck=Array.isArray(window.TAROT_CARDS)?window.TAROT_CARDS:[];if(!deck.length){toast('牌库正在准备中');return}const c=deck[Math.floor(Math.random()*deck.length)],rev=Math.random()<.35;$('#drawCard').hidden=true;$('#tarotResult').hidden=false;$('#cardGlyph').textContent='✦';$('#cardArcana').textContent='78 张完整牌库';$('#cardOrientation').textContent=rev?'逆位 · 内在提醒':'正位 · 当下力量';$('#cardName').textContent=c.name;$('#cardMeaning').textContent=rev?c.reversed:c.upright;$('#cardEmotion').textContent=c.emotionAnalysis||'留意此刻最先浮现的感受，它正在告诉你某种需要。';$('#cardSolution').textContent=c.careSuggestion||'先做一个足够小、不会增加负担的行动。';$('#cardQuestion').textContent=c.reflectionQuestion||'这张牌让你想到最近的哪一件事？'}
  $('#drawCard').addEventListener('click',drawTarot);$('#drawAgain').addEventListener('click',drawTarot);
  function openDialog(id){$(id).showModal()}$('#openAi').addEventListener('click',()=>openDialog('#aiDialog'));$('#openSafety').addEventListener('click',()=>openDialog('#safetyDialog'));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close()}));
  document.querySelector('.quick-prompts').addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;const replies={'先听我说':'我在听。你可以从“今天最难受的一刻”开始，慢慢写下来。','帮我梳理':'可以试试三句话：发生了什么？我感受到什么？我现在最需要什么？','给我一个小建议':'先把双脚踩稳地面，慢慢呼气。此刻只照顾接下来的十分钟。'};$('#aiMessages').innerHTML+=`<div class="ai-bubble" style="margin-top:10px">${replies[e.target.textContent]}</div>`});
  $('#today').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());renderMood();renderTriggers();renderCare();renderHistory();
})();
